apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orsapp-deployment-${TARGET_ROLE}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: orsapp
        role: ${TARGET_ROLE}
    spec:
      containers:
      - name: orsapp-container
        image: ${IMAGE_TAG}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
      imagePullSecrets:
      - name: ${KUBERNETES_SECRET_NAME}