kind: Service
apiVersion: v1
metadata:
  name: orsapp-service
  labels:
    app: orsapp
    role: ${TARGET_ROLE}
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: orsapp
    role: ${TARGET_ROLE}
  ports:
    - port: 80
      targetPort: 8080